name: Publish to Maven Central

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (optional, overrides VERSION_NAME)"
        required: false
        type: string

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses and install components
        shell: bash
        run: |
          yes | sdkmanager --licenses > /dev/null
          sdkmanager --install "platforms;android-35" "build-tools;35.0.0"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Publish (with explicit version)
        if: ${{ inputs.version != '' }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          chmod +x gradlew
          ./gradlew :fixedorder-staggered-grid-layoutmanager:publishMavenReleasePublicationToMavenRepository \
            -PVERSION_NAME=${{ inputs.version }} --no-daemon --stacktrace

      - name: Publish (use default version)
        if: ${{ inputs.version == '' }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          chmod +x gradlew
          ./gradlew :fixedorder-staggered-grid-layoutmanager:publishMavenReleasePublicationToMavenRepository \
            --no-daemon --stacktrace

      - name: Next steps
        run: |
          echo "If this is a release (not -SNAPSHOT), visit Sonatype to Close and Release the staged repository."

